// try{
//     console.log("hello")
//     console.log(a)
// } catch (err){
//     console.log("handled", err)
// } finally {
//     console.log("finally")
// }

// console.log("end")


try {
    let a = ["HELLO", "SAGAR "];
    console.log(a)
} catch (error) {
    console.log(`This is the Execution on catch`)
}